export const applications = [
  {
    num: "01",
    title: "Thermal Cleaning",
    slug: "thermal-cleaning",
    navSubtitle: "Remove plastics and organic compounds",
    shortDesc: "Fast and labor-efficient removal of all organic-based material from tooling and hardware using fluidized temperature baths.",
    heroImage: "/assets/images/tools/Tool%20%26%20Parts%20Cleaning.jpg",
    tags: ["TOOLING", "EXTRUSION", "MAINTENANCE", "CLEANING"],
    description: [
      "Accurate Thermal Systems fluidized baths clean metal parts by thermally removing all types of organic material, including plastic, paint, resin, adhesive, glue, oil, silicone, rubber, grease, food, and plant-based products. Fluidized baths offer a fast, safe, and efficient method to clean extrusion and injection molding parts.",
      "Fluidized baths are not grit or media blasters; they thermally burn off all organic material from metal parts and tooling. Our fluidized baths can be used to clean breaker plates, dies, injection nozzles, feed screws, hot runner parts, nozzles, die plates, extrusion profiles, screen changers, barrels, hooks, spin packs, tips, feed pipes, film extrusion dies, screw elements, molds, spinneret, hardware, pressure transducers, melt flow indexer dies, capillary rheometer parts, crossheads, die adaptor, screen pack, nuts and bolts, profile extrusion dies and many more types of parts.",
      "The thermal cleaning process typically takes 30 to 60 minutes to remove all material from the tooling. A fast and efficient cleaning cycle minimizes downtime during line change-outs and maintenance. The fluidized bath cleaning process does not require the operator\u2019s assistance after the part is placed into the bath, allowing them to move on to other duties.",
    ],
    benefits: [
      "Fast removal of organics from tooling, parts, and hardware in under 60 minutes, unlike 4 to 8 hours with burn-off and pyrolysis ovens",
      "Thermal cleaning is the most labor-efficient method to clean tooling \u2014 requires only 5 to 10 minutes per hour of labor for the cleaning process",
      "Unlike ultrasonic cleaning, no unsafe and hard-to-dispose chemicals or harsh solvents are needed",
      "Unlike torching, drilling, scraping, knives, lathes, and wire wheels, thermal cleaning does not damage expensive tooling",
      "Breaks down and removes organic-based material from small holes, orifices, channels, profiles, and openings down to 0.010\u2033",
      "Fluidizing action is gentle and will not abrade or change the surface finish of tooling and parts",
      "Complements other cleaning systems and speeds up line change-outs to minimize production downtime",
      "Removes all types of plastic and elastomers, including fluoropolymers, rubber, and silicone",
    ],
    relatedProducts: [
      { name: "Fluidized Temperature Baths", link: "/applications/extrusion-die-cleaning" },
      { name: "HEPA Air Filtration", link: "/applications/extrusion-die-cleaning" },
    ],
    beforeAfter: [
      {
        caption: "Sample 01",
        before: {
          src: "/assets/images/before-after/before-1.jpg",
          alt: "Customer tooling before thermal cleaning",
        },
        after: {
          src: "/assets/images/before-after/after-1.jpg",
          alt: "Customer tooling after thermal cleaning",
        },
      },
      {
        caption: "Sample 02",
        before: {
          src: "/assets/images/before-after/before-2.jpg",
          alt: "Customer part before thermal cleaning",
        },
        after: {
          src: "/assets/images/before-after/after-2.jpg",
          alt: "Customer part after thermal cleaning",
        },
      },
      {
        caption: "Sample 03",
        before: {
          src: "/assets/images/before-after/before-3.jpg",
          alt: "Customer component before thermal cleaning",
        },
        after: {
          src: "/assets/images/before-after/after-3.jpg",
          alt: "Customer component after thermal cleaning",
        },
      },
    ],
    customerCategory: "thermal-cleaning",
    video: {
      heading: "Thermal Cleaning in Action.",
      text: "Watch plastics, resin, and organic buildup thermally decompose and lift away from tooling in minutes \u2014 no solvents, no scraping, and no damage to expensive parts.",
      src: "/videos/estane-polymer-removal.mp4",
      poster: "/videos/posters/estane-polymer.jpg",
      title: "Fast Removal of Estane Polymer Using a Fluidized Bath",
    },
    ctaTitle: "Complimentary Sample Cleaning",
    ctaText: "Send us an example of your tooling for a complimentary cleaning. We\u2019ll perform a sample cleaning, produce a video of your part being cleaned, and ship it back within two days of receipt.",
  },
  {
    num: "02",
    title: "Nitinol Shape Setting & Heat Treatment",
    slug: "nitinol-shape-setting",
    navSubtitle: "Controlled heating for medical devices",
    shortDesc: "Stable and uniform temperature environments for nitinol shape setting, heat treatment, annealing, and medical device processing.",
    heroImage: "/assets/images/tools/heat-treatment-225x225.png",
    detailImage: {
      src: "/assets/images/tools/nitinol-heat-treatment-shape-setting.jpg",
      alt: "Nitinol Shape Setting and Heat Treatment",
    },
    tags: ["NITINOL", "MEDICAL DEVICES", "ANNEALING", "SHAPE SETTING"],
    description: [
      "Accurate Thermal Systems, a leader in medical device shape setting technology, offers several models of fluidized baths that provide very stable and uniform temperature environments for nitinol shape setting, heat treatment, annealing, tempering, thermal stress analysis, and heat setting of various metal components, parts, and assemblies.",
      "Some of the key applications are shape-setting nitinol stents, heat-setting medical devices, heat treatment and annealing of platinum and stainless steel guide wires, nitinol assemblies, tool cleaning for extruded medical products, and any other temperature applications that require the utmost stability and uniformity at temperatures up to 605\u00b0C.",
      "Fluidized baths offer excellent heat transfer due to the liquid-like properties of aluminum oxide that allow heat soak and overall manufacturing time to be minimized with predictable results. Fluidized aluminum oxide provides fast heat-up of immersed parts and objects three to four times faster than an oven without the required post-processing cleaning and safety concerns of molten salt baths.",
    ],
    benefits: [
      "Fully automatic fluidizing air control",
      "Advanced PID temperature controller",
      "Over-temperature limit protection",
      "RS485 computer interface",
      "Windows PC scheduler software",
      "Bath cover and lid system to retain heat and media",
      "Customizable lid can be modified to suspend devices and mandrels into the bath",
      "No jars to empty or dust extraction required \u2014 much safer than salt baths",
    ],
    relatedProducts: [
      { name: "Fluidized Temperature Baths", link: "/applications/thermal-cleaning" },
    ],
    customerCategory: "shape-setting",
    ctaTitle: "Complimentary Heat Treatment",
    ctaText: "Send us an example of your device or fixture for a complimentary heat treatment. We\u2019ll perform the heat treatment, produce a video of your part, and ship it back within two to three days of receipt.",
  },
  {
    num: "03",
    title: "Reactor Heating Methods",
    slug: "reactor-heating",
    navSubtitle: "Thermal support for process vessels",
    shortDesc: "Fast and efficient heating of laboratory and industrial reactors for research, development, and temperature-dependent reactions.",
    heroImage: "/assets/images/tools/reactor-heating-225x225.png",
    detailImage: {
      src: "/assets/images/tools/reactor-heating-methods.jpg",
      alt: "Reactor Heating Methods",
    },
    tags: ["RESEARCH", "REACTORS", "PROCESS HEAT", "LABORATORY"],
    description: [
      "Fortune 500 companies and university biochemistry and engineering departments use fluidized temperature baths for fast and efficient heating of many processes, including heating reactors and coils for dependable endothermic and exothermic reactions.",
      "Their large working volume, thermal capacity, temperature stability, and uniformity make them an optimal heating solution for laboratory and industrial applications. Fluidized temperature baths offer excellent heat transfer because aluminum oxide\u2019s liquid-like properties minimize heat soak and overall reaction times, providing expected results, unlike traditional laboratory ovens that are not as thermally responsive.",
      "The aluminum oxide media in a fluidized bath is inert, providing a safer operating environment, whereas salt baths are highly corrosive and very dangerous due to the risk of explosion when moisture is present. Any of our fluidized bath models can be used for reactor heating depending on the volume and size required.",
    ],
    benefits: [
      "Large working volume and high thermal capacity for process heating",
      "Temperature stability and uniformity for dependable reactions",
      "Inert aluminum oxide media \u2014 safer than salt baths",
      "Faster heat transfer than traditional laboratory ovens",
      "Suitable for endothermic and exothermic reactions",
      "Works with custom reactor coils, biomass reactors, jacketed reactors, and Parr reactors",
      "Models available up to 1100\u00b0C for high-temperature applications",
      "Cryogenic models available down to -100\u00b0C",
    ],
    relatedProducts: [
      { name: "Fluidized Temperature Baths", link: "/applications/thermal-cleaning" },
    ],
    customerCategory: "reactor-heating",
    ctaTitle: "Discuss Your Application",
    ctaText: "Contact us to discuss your reactor heating application and determine which fluidized temperature bath model is the best fit for your process.",
  },
  {
    num: "04",
    title: "Temperature Calibration",
    slug: "temperature-calibration",
    navSubtitle: "Stable environments for sensors",
    shortDesc: "Choice of temperature sources for calibrating temperature sensors, thermometers, indicators, systems, and probes.",
    heroImage: "/assets/images/tools/calobrationp-225x225.png",
    detailImage: {
      src: "/assets/images/tools/thermcal400.jpg",
      alt: "ThermCal dry block temperature calibrator",
    },
    tags: ["SENSORS", "LABORATORY", "TESTING", "CALIBRATION"],
    description: [
      "We offer a choice of temperature sources for calibrating temperature sensors, thermometers, indicators, systems, and probes. Our dry block temperature calibrators and fluidized temperature baths provide stable, accurate thermal environments for calibration workflows.",
      "Our dry block temperature calibrators consist of a drilled metal block with a large well for accepting an insert. Some models have a well for an insert and a fixed 1/4\u2033 hole for inserting a temperature reference probe. Inserts can have one or many different hole sizes and can be machined for tapered and custom probe sizes.",
      "With a large working volume and high heat capacity, our fluidized temperature baths are ideal for simultaneously calibrating multiple sensors and/or larger sensors with a tapered or odd sheath. Various models can operate at high temperatures up to 1000\u00b0C and as low as -100\u00b0C.",
    ],
    benefits: [
      "Portable and lightweight dry block calibrators for field use",
      "Fast heat up and cool down times",
      "Excellent display accuracy",
      "Large volume fluidized baths for calibrating multiple sensors simultaneously",
      "Wide temperature range from -100\u00b0C to 1000\u00b0C",
      "Safer than salt baths \u2014 inert aluminum oxide media",
      "More stable and uniform than ovens",
      "Clean and easy to use",
    ],
    relatedProducts: [
      { name: "Fluidized Temperature Baths", link: "/applications/thermal-cleaning" },
      { name: "ThermCal Dry Block Calibrators", link: "/applications/thermal-cleaning" },
    ],
    customerCategory: "calibration",
    ctaTitle: "Request Calibration Guidance",
    ctaText: "Contact us to discuss your temperature calibration requirements and find the right thermal source for your sensors and instrumentation.",
  },
  {
    num: "05",
    title: "Extrusion Die Cleaning",
    slug: "extrusion-die-cleaning",
    navSubtitle: "Fast, Uniform Polymer Removal from Extrusion Dies",
    shortDesc: "Reduce the time and labor required to clean plastic extrusion dies — fluidized bath thermal processing removes polymer from holes, flow passages, and grooves without damaging tooling.",
    heroImage: "/assets/images/tools/Tool%20%26%20Parts%20Cleaning.jpg",
    tags: ["EXTRUSION DIES", "POLYMER REMOVAL", "TOOLING", "FLUIDIZED BATH"],
    description: [
      "Extrusion dies require regular cleaning to maintain product quality, dimensional consistency, and reliable production. Polymer can accumulate on die surfaces and inside flow passages. As material degrades or hardens, manual removal can become increasingly difficult and time-consuming.",
      "Traditional cleaning may require scraping, drilling, wire brushing, hand tools, extended oven cycles, and repeated disassembly and manual cleanup. Fluidized bath thermal cleaning provides a controlled alternative: the entire die is surrounded by hot, fluidized aluminum oxide media, transferring heat rapidly and uniformly throughout the tooling.",
      "The polymer thermally decomposes, leaving a dry, non-binding residue that can typically be removed after cooling with light brushing and compressed air.",
    ],
    complexGeometry: {
      heading: "Clean Complex Die Geometry",
      text: "One of the major challenges with extrusion die cleaning is reaching areas that are difficult to access manually. Fluidized media surrounds the external surfaces of the tooling while heat conducts throughout the die \u2014 making the process particularly useful for components containing internal flow passages, small openings, grooves, slots, complex profiles, recessed areas, and multiple polymer flow paths. Instead of manually trying to reach every contaminated surface, the complete tooling assembly is exposed to a controlled thermal process.",
    },
    process: [
      { step: "1", title: "Prepare the Die", text: "The die is disassembled as necessary and reviewed for size, weight, tooling material, and polymer type." },
      { step: "2", title: "Heat the Fluidized Bath", text: "Aluminum oxide media is fluidized with compressed air and heated to the selected cleaning temperature." },
      { step: "3", title: "Load the Die", text: "The die or individual tooling components are placed in a basket or suitable fixture and lowered into the fluidized bath." },
      { step: "4", title: "Thermally Remove the Polymer", text: "Rapid, uniform heat transfer brings the tooling to process temperature and thermally breaks down the polymer." },
      { step: "5", title: "Remove & Cool", text: "The tooling is removed from the bath and allowed to cool safely." },
      { step: "6", title: "Final Cleanup", text: "Remaining non-binding residue and loose aluminum oxide can typically be removed using a soft brush and compressed shop air." },
    ],
    benefits: [
      "No more scraping, drilling, wire brushing, or hand-tool cleanup",
      "No more extended oven cycles or repeated disassembly",
      "Fluidized media reaches internal flow passages, small openings, grooves, slots, and recessed areas manual tools can't access",
      "Rapid, uniform heat transfer processes the entire die at once \u2014 not surface by surface",
      "Leaves a dry, non-binding residue removable with light brushing and compressed air",
      "Gentle fluidizing action preserves die geometry and surface finish",
      "Reduces the time and labor required for routine die maintenance",
      "Correct bath size is matched to your die's size, weight, and load",
    ],
    relatedProducts: [
      { name: "Fluidized Temperature Baths", link: "/applications/thermal-cleaning" },
      { name: "HEPA Air Filtration", link: "/applications/thermal-cleaning" },
    ],
    customerCategory: "thermal-cleaning",
    ctaTitle: "Free Cleaning Trial",
    ctaText: "Send us your die for a free cleaning trial. We\u2019ll clean it, show you the results, and help you identify the correct fluidized bath system based on your die's size and load.",
  },
  {
    num: "06",
    title: "Extruder Screw Cleaning",
    slug: "extruder-screw-cleaning",
    navSubtitle: "Clean polymer from extruder screws with less manual work",
    shortDesc: "Thermal cleaning breaks down polymer from screw flights, roots, and mixing sections, reducing scraping and handling.",
    heroImage: "/assets/images/tools/Tool%20%26%20Parts%20Cleaning.jpg",
    tags: ["EXTRUDER SCREWS", "POLYMER REMOVAL", "TOOLING", "FLUIDIZED BATH"],
    description: [
      "Polymer builds up around screw flights, roots, grooves, mixing sections, and other hard-to-reach areas.",
      "Fluidized bath cleaning heats the screw in moving aluminum oxide, breaking down polymer before light cleanup.",
      "After cooling, remove the dry residue with a brush and compressed air.",
    ],
    complexGeometry: {
      heading: "Clean Between Flights and Mixing Sections",
      text: "Heated aluminum oxide surrounds the screw and transfers heat to flights, roots, grooves, and mixing sections. Polymer breaks down during processing; dry residue is removed after cooling.",
    },
    process: [
      { step: "1", title: "Review the Screw", text: "Check diameter, length, weight, material, coating, polymer, and buildup." },
      { step: "2", title: "Heat the Fluidized Bath", text: "Heat the fluidized media to the selected process temperature." },
      { step: "3", title: "Load the Screw", text: "Place the screw in a suitable basket or fixture. Process long screws in sections when needed." },
      { step: "4", title: "Break Down the Polymer", text: "Heat transfers to the submerged screw surfaces and breaks down polymer." },
      { step: "5", title: "Remove & Cool", text: "Remove the screw and let it cool safely." },
      { step: "6", title: "Final Cleanup", text: "Remove loose residue and media with a soft brush and compressed air." },
    ],
    benefits: [
      "Less scraping",
      "Access to flights, roots, grooves, and mixing sections",
      "Rapid heat transfer",
      "Even exposure around submerged surfaces",
      "Repeatable routine cleaning",
      "Less operator time",
      "Section cleaning for long screws",
      "Minimal mechanical contact",
    ],
    relatedProducts: [
      { name: "Fluidized Temperature Baths", link: "/products/fluidized-temperature-baths" },
      { name: "HEPA Air Filtration", link: "/products/hepa-air-filtration" },
    ],
    customerCategory: "thermal-cleaning",
    ctaTitle: "Free Cleaning Trial",
    ctaText: "Send your screw for a free cleaning trial. We'll help select the right bath and process.",
    extendedContent: {
      hero: {
        title: "Extruder Screw Cleaning Without Heavy Scraping",
        primaryCta: "Request a Free Screw Cleaning Trial",
        secondaryCta: "View Fluidized Bath Systems",
      },
      overview: {
        eyebrow: "01 / BUILDUP AREAS",
        heading: "Clean Between Flights and Mixing Sections",
        buildupAreas: [
          "Screw flights",
          "Screw roots",
          "Mixing sections",
          "Metering sections",
          "Feed sections",
          "Grooves",
          "Tips",
          "Other screw geometry",
        ],
      },
      benefits: {
        eyebrow: "02 / WHY FLUIDIZED BATH CLEANING?",
        heading: "Why Fluidized Bath Cleaning?",
        items: [
          { title: "Reduce Scraping", text: "Break down polymer before it must be scraped." },
          { title: "Reach Complex Areas", text: "Heat reaches flights, roots, grooves, and mixing sections." },
          { title: "Fast Heat Transfer", text: "Moving aluminum oxide heats the screw quickly." },
          { title: "Even Exposure", text: "Media surrounds submerged surfaces for consistent processing." },
          { title: "Repeatable Results", text: "Set temperature, time, loading, and airflow for routine cleaning." },
          { title: "Reduce Labor", text: "Reduce manual scraping and brushing." },
        ],
      },
      process: {
        eyebrow: "04 / SIX-STEP PROCESS",
        heading: "How Extruder Screw Cleaning Works",
        media: {
          src: "/assets/images/fluidized/lid-basket.jpg",
          alt: "Lid and basket assembly for loading tooling into a fluidized temperature bath",
          label: "FLUIDIZED BATH / LOADING",
        },
      },
      polymers: {
        eyebrow: "05 / POLYMER OPTIONS",
        heading: "Cleaning Different Polymers",
        intro: "Process selection depends on the polymer, screw material, and buildup.",
        items: [
          { name: "PVC & CPVC", text: "Confirm temperature and exhaust requirements.", cta: "PVC / CPVC Removal" },
          { name: "Polyethylene & Polypropylene", text: "Common buildup areas include flights, roots, and mixing sections.", cta: "PE / PP Removal" },
          { name: "Nylon", text: "Often difficult to remove after cooling or degradation.", cta: "Nylon Removal" },
          { name: "PEEK & High-Temperature Polymers", text: "Use a controlled trial to establish the process.", cta: "PEEK Removal" },
          { name: "Other Organic Materials", text: "Submit the polymer and screw details for evaluation.", cta: "Ask ATS About Your Polymer" },
        ],
      },
      screwLength: {
        eyebrow: "06 / BATH DEPTH",
        heading: "Match the Bath to Screw Length",
        paragraphs: [
          "Screw length determines the bath working depth and loading plan.",
          "Long screws may be cleaned in sections or processed in a deeper bath.",
          "A deeper bath can reduce loading positions and handling time.",
          "For frequent cleaning, balance screw dimensions, facility space, and budget.",
        ],
        cta: "Send Us Your Screw Dimensions",
      },
      sectionalCleaning: {
        eyebrow: "07 / SECTIONAL CLEANING",
        heading: "Clean Long Screws in Sections",
        intro: "When the screw exceeds bath depth, process sections sequentially.",
        factors: [
          "Screw length",
          "Bath working depth",
          "Required overlap",
          "Polymer condition",
          "Screw geometry",
          "Handling method",
        ],
        occasional: "Best for occasional cleaning.",
        frequent: "A deeper bath can reduce handling for frequent cleaning.",
        cta: "Send Us Your Screw Dimensions",
      },
      surfaceTreatment: {
        eyebrow: "08 / MATERIALS & COATINGS",
        heading: "Check Screw Material and Coatings",
        paragraphs: [
          "Screws may use hardened steel, nitriding, chrome plating, or specialty coatings.",
          "Confirm material, surface treatment, temperature, and exposure time before processing.",
          "Use a first trial to validate critical or specialty screws.",
        ],
      },
      temperature: {
        eyebrow: "09 / PROCESS TEMPERATURE",
        heading: "Select a Safe, Effective Temperature",
        paragraphs: [
          "Temperature depends on the polymer and screw construction.",
          "Start with the lowest temperature that removes the polymer within the required cycle.",
        ],
        considerations: [
          "Polymer type",
          "Polymer thickness",
          "Screw material",
          "Surface treatment",
          "Tool hardness",
          "Amount of buildup",
          "Required cleaning time",
        ],
        closing: "Confirm the process with a representative screw trial.",
        cta: "Request a Cleaning Trial",
      },
      manualComparison: {
        eyebrow: "10 / CLEANING METHODS",
        heading: "Fluidized Bath vs. Manual Cleaning",
        columns: ["Comparison", "Fluidized Bath", "Manual Cleaning"],
        rows: [
          ["Primary removal", "Thermal breakdown", "Scraping / brushing"],
          ["Screw flights", "Thermally processed", "Manual access"],
          ["Mixing sections", "Thermally processed", "Difficult access"],
          ["Operator labor", "Low after processing", "High"],
          ["Repeatability", "Controlled process", "Operator dependent"],
          ["Multiple components", "Possible", "Limited"],
          ["Mechanical contact", "Minimal", "Direct tool contact"],
        ],
        cta: "Compare Cleaning Methods",
      },
      ovenComparison: {
        eyebrow: "11 / HEAT TRANSFER",
        heading: "Fluidized Bath vs. Burn-Off Oven",
        paragraphs: [
          "Both use heat to remove organic material.",
          "Burn-off ovens use hot circulating air; fluidized baths use heated, moving aluminum oxide.",
          "Fluidized media transfers heat rapidly around submerged tooling.",
          "Choose the process that fits your tooling, cycle time, and labor goals.",
        ],
        cta: "Compare Heat Transfer Methods",
      },
    },
  },
];

export function getApplicationBySlug(slug) {
  return applications.find((app) => app.slug === slug);
}

export function getAllSlugs() {
  return applications.map((app) => app.slug);
}
