export const breakerPlateContent = {
  hero: {
    eyebrow: "THERMAL CLEANING / BREAKER PLATES",
    title: "Breaker Plate Cleaning with Fluidized Temperature Baths",
    primaryCta: "Send Your Breaker Plate for a Free Cleaning Trial",
    secondaryCta: "View Fluidized Bath Systems",
    videoLabel: "BREAKER PLATE / BEFORE → BATH → OPEN HOLES",
  },
  problem: {
    eyebrow: "01 / THE MANUAL CLEANING PROBLEM",
    heading: "Stop Cleaning Every Hole by Hand",
    intro: "Breaker plates are designed with multiple flow passages that can become packed with hardened or degraded polymer. Cleaning them manually may involve:",
    manualMethods: [
      "Drilling individual holes",
      "Scraping hardened polymer",
      "Using picks and hand tools",
      "Wire brushing",
      "Repeated heating and cleaning",
      "Significant operator time",
    ],
    difficulty: "The problem becomes greater as breaker plate diameter, thickness, hole count, and polymer temperature resistance increase.",
    thermalIntro: "Fluidized bath thermal cleaning attacks the problem differently. Instead of mechanically removing polymer from each individual opening, the complete breaker plate is exposed to a controlled thermal process. Heat is transferred rapidly throughout the plate, thermally breaking down the polymer in the holes and passages.",
    thermalOutro: "After processing, the remaining residue is non-binding and can typically be blown or brushed from the passages.",
    applications: [
      "Large numbers of holes",
      "Small-diameter passages",
      "Deep holes",
      "Thick plates",
      "Hardened polymer",
      "High-temperature polymers",
      "Complex flow patterns",
    ],
  },
  benefits: {
    eyebrow: "02 / WHY FLUIDIZED BATH CLEANING?",
    heading: "Why Breaker Plates Are Ideal for Fluidized Bath Cleaning",
    items: [
      {
        title: "Clean Many Holes at the Same Time",
        text: "The entire breaker plate is thermally processed at once rather than cleaning one passage at a time.",
      },
      {
        title: "Reduce Drilling & Scraping",
        text: "Minimize the need to manually drill, pick, or scrape polymer from individual holes.",
      },
      {
        title: "Reach Deep Passages",
        text: "Thermal processing does not rely on direct physical access to every contaminated surface.",
      },
      {
        title: "Fast, Uniform Heating",
        text: "Fluidized aluminum oxide transfers heat efficiently around the plate.",
      },
      {
        title: "Repeatable Cleaning",
        text: "Once the appropriate process parameters are established, the same cleaning procedure can be repeated for routine production maintenance.",
      },
      {
        title: "Process Multiple Plates",
        text: "Depending on breaker plate size, weight, and bath capacity, multiple plates may be cleaned during the same batch.",
      },
    ],
  },
  process: {
    eyebrow: "03 / HOW BREAKER PLATE CLEANING WORKS",
    heading: "How Breaker Plate Cleaning Works",
    steps: [
      {
        step: "01",
        title: "Review the Breaker Plate",
        text: "ATS evaluates the breaker plate diameter, thickness, weight, hole configuration, tooling material, and polymer being removed.",
      },
      {
        step: "02",
        title: "Heat the Fluidized Bath",
        text: "Aluminum oxide media is fluidized with compressed air and heated to the selected process temperature.",
      },
      {
        step: "03",
        title: "Load the Breaker Plate",
        text: "The plate is placed into a basket or suitable fixture and lowered into the fluidized bath.",
      },
      {
        step: "04",
        title: "Thermally Break Down the Polymer",
        text: "The hot fluidized media provides rapid heat transfer to the breaker plate. As the plate reaches process temperature, polymer on the surfaces and inside the holes begins to thermally decompose.",
      },
      {
        step: "05",
        title: "Remove & Cool",
        text: "After the cleaning cycle, the breaker plate is removed and allowed to cool.",
      },
      {
        step: "06",
        title: "Final Cleanup",
        text: "Remaining loose residue and aluminum oxide are removed using a soft brush and compressed shop air. The holes can then be visually inspected to confirm they are open.",
      },
    ],
  },
  polymers: {
    eyebrow: "04 / CLEANING DIFFERENT POLYMERS",
    heading: "Cleaning Different Polymers from Breaker Plates",
    intro: "Breaker plates are used with a wide range of extrusion materials. Fluidized bath cleaning can be evaluated for materials including:",
    items: [
      {
        name: "PVC & CPVC",
        text: "Used extensively in pipe, profile, and other extrusion applications. PVC processing requires appropriate temperature control and exhaust consideration.",
        cta: "PVC / CPVC Removal",
      },
      {
        name: "Polyethylene & Polypropylene",
        text: "Common materials in film, sheet, pipe, packaging, profile, and general extrusion applications.",
        cta: "PE / PP Removal",
      },
      {
        name: "Nylon",
        text: "Nylon residue can become difficult to remove from small breaker plate passages using manual methods.",
        cta: "Nylon Removal",
      },
      {
        name: "PEEK & High-Temperature Polymers",
        text: "High-temperature polymers can be particularly difficult and labor-intensive to remove mechanically.",
        cta: "PEEK Removal",
      },
    ],
    otherText: "Other polymers and organic materials may also be suitable.",
    otherCta: "Ask ATS About Your Material",
  },
  temperature: {
    eyebrow: "05 / CLEANING TEMPERATURE",
    heading: "What Cleaning Temperature Should Be Used?",
    intro: "There is no single temperature that is correct for every breaker plate. The starting process depends on:",
    considerations: [
      "Polymer type",
      "Amount of polymer",
      "Breaker plate material",
      "Tooling hardness / heat treatment",
      "Plate thickness",
      "Hole dimensions",
      "Required cleaning time",
      "Previous cleaning method",
    ],
    recommendations: [
      "ATS recommends using the lowest practical temperature that provides effective polymer removal within an acceptable cleaning cycle.",
      "For a new application, a cleaning trial is the best way to establish a practical starting temperature and processing time.",
    ],
    cta: "Send a Breaker Plate for a Trial",
  },
  hardness: {
    eyebrow: "06 / MATERIALS & HARDNESS",
    heading: "Protecting Breaker Plate Hardness",
    intro: "Breaker plates and extrusion tooling may be manufactured from hardened steels or other heat-treated materials. Any elevated-temperature thermal cleaning process should therefore consider the original tooling material and heat treatment.",
    factors: [
      "Steel or alloy",
      "Original heat treatment",
      "Tempering temperature",
      "Current hardness",
      "Cleaning temperature",
      "Time at temperature",
      "Number of repeated cleaning cycles",
    ],
    paragraphs: [
      "Fluidized baths provide rapid heat transfer, which can help minimize unnecessary time at elevated temperature compared with slower heating processes.",
      "For critical hardened tooling, ATS recommends verifying material and hardness requirements and using the lowest effective cleaning temperature. When appropriate, hardness can also be checked before and after initial cleaning trials.",
    ],
  },
  manualComparison: {
    eyebrow: "07 / CLEANING METHODS",
    heading: "Breaker Plate Cleaning vs. Manual Drilling",
    intro: [
      "Manually drilling every breaker plate hole may remove polymer, but it requires operator time and physical access to each passage. It can also introduce the possibility of mechanical contact with the hole surfaces.",
      "Fluidized bath cleaning uses heat rather than a drill bit to break down the polymer.",
    ],
    columns: ["Comparison", "Fluidized Bath", "Manual Drilling / Picking"],
    rows: [
      ["Cleans all holes together", "Yes", "No"],
      ["Requires access to each hole", "No", "Yes"],
      ["Operator labor", "Low after processing", "High"],
      ["Deep passages", "Thermally processed", "Must be physically reached"],
      ["Batch processing", "Yes", "No"],
      ["Repeatable process", "Yes", "Operator dependent"],
      ["Mechanical contact inside holes", "Minimal", "Direct tool contact"],
    ],
    cta: "Fluidized Bath vs. Mechanical Cleaning",
  },
  ovenComparison: {
    eyebrow: "08 / HEAT TRANSFER",
    heading: "Breaker Plate Cleaning vs. Burn-Off Oven",
    paragraphs: [
      "Both processes use heat to decompose polymer. The primary difference is heat transfer.",
      "Burn-off ovens primarily heat components through hot circulating air. Fluidized baths surround the breaker plate with hot, moving aluminum oxide media, producing rapid heat transfer around the component.",
      "This can allow breaker plates to reach the required cleaning temperature quickly and complete the cleaning process in a shorter, controlled thermal cycle.",
    ],
    cta: "Fluidized Bath vs. Burn-Off Oven",
  },
  trial: {
    eyebrow: "09 / SEE A BREAKER PLATE CLEANING TRIAL",
    heading: "Real Parts. Real Polymer. Real Results.",
    intro: "The easiest way to evaluate fluidized bath cleaning is to send ATS one of your used breaker plates. We can evaluate:",
    items: [
      "Breaker plate dimensions",
      "Number and size of holes",
      "Plate weight",
      "Polymer being removed",
      "Cleaning temperature",
      "Cleaning time",
      "Final hole condition",
      "Required final cleanup",
      "Recommended bath size",
    ],
    closing: "We can document the cleaning trial with photos or video so your team can review the process and results.",
    videoLabel: "FEATURED VIDEO / BREAKER PLATE CLEANING",
    photoLabel: "BEFORE / AFTER / CLOSE-UP OF HOLES",
    cta: "Watch More Thermal Cleaning Videos",
  },
  bathModels: {
    eyebrow: "10 / SYSTEM SELECTION",
    heading: "Which Fluidized Bath Fits Your Breaker Plates?",
    intro: "System selection should be based on the breaker plate diameter, thickness, weight, and number of plates you want to process per batch.",
    models: [
      {
        name: "FTBLL12",
        text: "Working area approximately 8-3/8 in. diameter × 12–13 in. deep. Suitable for smaller breaker plates and tooling. Typical thermal load: approximately 25 lb.",
        cta: "View FTBLL12",
      },
      {
        name: "FTBLL12W",
        text: "Working area approximately 12-3/8 in. diameter × 13 in. deep. The wider chamber is well suited to larger-diameter breaker plates and allows easier loading of shorter, wider components. Typical thermal load: approximately 60 lb.",
        cta: "View FTBLL12W",
      },
      {
        name: "FTBLL26",
        text: "Working area approximately 8-3/8 in. diameter × 26 in. deep. Useful when breaker plate cleaning is combined with longer extrusion tooling. Typical thermal load: approximately 50 lb.",
        cta: "View FTBLL26",
      },
      {
        name: "FTBLL27",
        text: "Working area approximately 15.7 in. diameter × 27–28 in. deep. Designed for larger-diameter breaker plates, heavier tooling, and higher-capacity production cleaning. Typical thermal load: approximately 130 lb.",
        cta: "View FTBLL27",
      },
    ],
    largerText: "ATS can evaluate larger or custom configurations for breaker plates that exceed standard bath dimensions or thermal loads.",
    largerCta: "Compare All Fluidized Bath Models",
  },
  batchCapacity: {
    eyebrow: "11 / BATCH CAPACITY",
    heading: "How Many Breaker Plates Can You Clean at Once?",
    intro: "Batch capacity depends on more than whether the plates physically fit inside the chamber. ATS considers:",
    factors: [
      "Individual plate diameter",
      "Plate thickness",
      "Individual weight",
      "Total batch weight",
      "Space between components",
      "Required media circulation",
      "Polymer load",
      "Desired cycle time",
    ],
    closing: "Multiple breaker plates can often be stacked in a multi-tier basket or custom fixture while maintaining appropriate spacing for the cleaning process. ATS can recommend a basket configuration based on your actual breaker plate dimensions and production volume.",
    photoLabel: "MULTI-TIER BASKET WITH BREAKER PLATES",
    cta: "Ask About Custom Baskets",
  },
  system: {
    eyebrow: "12 / COMPLETE SYSTEM",
    heading: "Complete Breaker Plate Cleaning System",
    components: [
      { name: "Fluidized Temperature Bath", text: "Provides rapid, controlled thermal cleaning." },
      { name: "Standard or Multi-Tier Basket", text: "Allows one or multiple breaker plates to be loaded and removed safely." },
      { name: "Aluminum Oxide Media", text: "Provides fluidization and heat transfer." },
      { name: "Cyclone", text: "Helps remove larger particulate from the exhaust stream." },
      { name: "HEPA Filtration", text: "Captures fine particulate." },
      { name: "Activated Carbon Filtration", text: "Can help reduce odors and selected organic vapors." },
      { name: "Facility Exhaust", text: "Final exhaust design depends on the polymers being processed and applicable facility requirements. Some materials may require additional exhaust treatment." },
    ],
    cta: "Explore Air Filtration",
    secondaryCta: "View Baskets & Accessories",
    diagram: ["Bath", "Cyclone", "HEPA / Carbon", "Facility Exhaust"],
  },
  contact: {
    eyebrow: "13 / SEND US ONE OF YOUR DIRTY BREAKER PLATES",
    heading: "See How It Cleans Before You Purchase a System",
    intro: "You do not have to estimate whether fluidized bath cleaning will work for your application. Send ATS a representative breaker plate. Please provide:",
    fields: [
      "Outside diameter",
      "Thickness",
      "Approximate weight",
      "Hole diameter",
      "Approximate number of holes",
      "Breaker plate material, if known",
      "Polymer being removed",
      "Current cleaning method",
      "Cleaning frequency",
      "Photos or drawings",
    ],
    closing: "ATS can perform a cleaning trial, document the results, and recommend the appropriate system for your operation.",
    closingHeading: "Stop Cleaning Every Hole by Hand.",
    cta: "Send Your Breaker Plate for a Free Cleaning Trial",
  },
  related: [
    { name: "Extrusion Die Cleaning", href: "/applications/extrusion-die-cleaning" },
    { name: "Extruder Screw Cleaning", href: "/applications/extruder-screw-cleaning" },
    { name: "PVC / CPVC Removal", href: "#breaker-plate-polymers" },
    { name: "Nylon Removal", href: "#breaker-plate-polymers" },
    { name: "PEEK Removal", href: "#breaker-plate-polymers" },
    { name: "PE / PP Removal", href: "#breaker-plate-polymers" },
    { name: "All Thermal Cleaning Applications", href: "/applications/thermal-cleaning" },
  ],
};
